spring: 
  cloud: 
    stream:
      function:
        definition: processHello
      bindings: 
        processHello-in-0: 
          destination: hello-strings
          group: hello-strings-group
          consumer: 
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000 
        processHello-0: 
          destination: hello-strings-processed
